### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [MRSIMM0/oop-put-course#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Rename repository to **oop-put-course**
- [ ] Rename file to task1.cpp
